const ResponseCodes = {
  SUCCESS: "0",
  GEN__SERVER_ERROR: "gen-1001",
  AUTH__REGISTRATION_SUCCESSFUL: "auth-0001",
  AUTH__LOGIN_SUCCESSFUL: "auth-0002",
  AUTH__EMAIL_ALREADY_EXISTS: "auth-1001",
  AUTH__CREDENTIALS_ARE_INCORRECT: "auth-1002",
  AUTH__UNAUTHORIZED_ACCESS: "auth-1003",
  PROF__FETCHED_SUCCESSFULLY: "prof-0001",
  FAILED: "1",
};

export default ResponseCodes;
